version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: template-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local

